[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "This ones mine"
logo = "images/blog.jfif"
favicon = "images/ico.png"
primaryColor = "#F89616"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[data.ai_csv]
type = "csv"
path = "data/ai.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
